// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euqbhzaojslaipxmebnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1cWJoemFvanNsYWlweG1lYm5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDkwNzgsImV4cCI6MjA3NDA4NTA3OH0.T_uj8cLLXWrgOuUknD1QJ2FVcsWeSK-CWfV3OLFbHCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});